### ISSUE TITLE
EPIC - Cheat Sheets

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#1]
- [ ] Runtime - Accounts, TXs, Gas, Units
- [ ] Rust development
- [ ] AssemblyScript development
- [ ] EVM
- [ ] Bridge
- [ ] near-api-js, near-cli

We need "cheat sheets" for the following topics in NEAR.

Community discussion here: https://gov.near.org/t/epic-cheat-sheets/392

**Comment by thisisjoshford** [comment]
Community member request from discord:
- cost of a simple delegation
- cost of simple NEAR transfer
- cost of NEP-21 transfer (assuming no new storage is created)
- cost of NEP-141 transfer (assuming a basic implementation)

**Comment by think-in-universe** [comment]
Some initial thoughts about the cheat sheet which we could elaborate later. 

## Why Near Cheat Sheet?

The purpose of this Cheat Sheet is to serve as a quick reference where a developer could look up information efficiently when building a DApp or smart contract. The developer can print out the Cheat Sheet with a A4 format paper in 1 ~ 2 pages, and put it besides his/her laptop or desktop if needed. 

We would probably assume the reader of the cheat sheet has already learnt some basic concepts about Near via [courses such as Near 101](https://www.crowdcast.io/near), or [Near developer docs](https://docs.near.org/docs/roles/developer/quickstart)


## Cheat Sheet Design

We don't need to plan and start with a perfect version in the 1st iteration. We could easily launch with some of the main concepts, knowledge, units, tips, etc., just like those that are usually not easy to memorize before an exam. 

### Outline

Below are some examples of the content to be filled into the cheat sheet. 

1. concepets & infra
    1. runtime: 
        1. account
        2. transaction
        3. action: CreateAccount / DeleteAccount / AddKey / DeleteKey / Transfer / Stake / DeployContract / FunctionCall
        4. gas: 
        5. units:  yocht Ⓝ
    2. network: mainnet / testnet / betanet / localnet
2. languages
    1. AssemblyScript: 
        1. data types: `u128`, `u256` 
    3. Rust: 
3. frameworks & practices
    1. `near-sdk-rs`
    2. `near-sdk-as`
    3. `near-api-js` 
4. development environment
    1. `npx create-near-app <project>`: create a new project
    2. `near-cli`
        1. 
    3. VSCode extension (if available)
5. testing
    1. `as-pect`
6. build & ship & monitoring
    1. build: 
    2. deploy: 
7. security
    1. `#[payable]`
8. integration & interoperability
    1. bridge
    2. EVM
    3. tools


### Localization

- Russian version
- Chinese version


## Relevant Ideas

### Cheat Sheets

- **Rust** Cheat Sheet: https://cheats.rs/
- **AssemblyScript** Cheat Sheet -- WASM to TS: https://github.com/AssemblyScript/assemblyscript/wiki/WebAssembly-to-TypeScript-Cheat-Sheet
- **Ethereum** Cheat Sheet 1: https://intellipaat.com/mediaFiles/2019/02/Ethereum-Cheat-Sheet-1.png (from the [page](https://intellipaat.com/blog/tutorial/blockchain-tutorial/ethereum-cheat-sheet/))
- **Ethereum** Cheat Sheet 2: https://github.com/beether/ethereum-dev-cheatsheet#cb

### Awesome List

Awesome Near

- https://github.com/near/awesome-near
- https://awesomenear.com/
