### ISSUE TITLE
[EPIC] Partnerships

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#105]
# Proposal for: Ecosystem partnerships

## What is this? 
- See above

## Who needs to be involved?
-Dani + maybe engineers ad hoc

## What t-shirt size is this? (range: multi-spint to 1 hour)
Large

## What priority is this? (remove what doesn't apply)
- P1

**Comment by cameron-NEAR** [comment]
I'd love to know who we're partnering with whenever things are close to being finalized :)
