### ISSUE TITLE
[TASK] Paper some grants

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#106]
# Proposal for: Determine milestones and timelines for pending grants

## What is this? 
- As requested by ET, need to paper up some grants for past cases that pre-date the official Pilot Program. 

## Who needs to be involved?
-Dani, Sonya, and Gus.

## Tasks to complete (can return to [x] these)
- [ ] Gather milestones & Timelines
- [ ] Draft up documents

## What t-shirt size is this? (range: multi-spint to 1 hour)
 Medium

## What priority is this? (remove what doesn't apply)
- P2

**Comment by crasskitty** [comment]
I trust in @waverlymaven , and agree this is a p2 medium. :)
