### ISSUE TITLE
[EPIC] Cameron Project Sourcing

### ISSUE THREAD

**Issue by cameron-NEAR** [near/devrel#111]
# Proposal for: Cameron Project Sourcing 

## What is this? 
- Identify, contact, and manage inbound projects interested in building on NEAR. Currently leads are FRAX, Web 3 API, AI Foundation, BOLT, Geer, and some oracle provider. 

## Who needs to be involved?
- @cameron-NEAR 

## Tasks to complete (can return to [x] these)
- [Manage relationships and get people to submit grants]
- [Reach out to three new companies] 

## What t-shirt size is this? (range: multi-spint to 1 hour)
(medium)

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)

**Comment by crasskitty** [comment]
@cameron-NEAR are you working with the new BD team on this?

**Comment by doriancrutcher** [comment]
I'd love to hear more about how dev rel currently goes about finding new partners to work with.
