### ISSUE TITLE
[EPIC] BlockHead Community Stories - City Council Memeber

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#114]
# Proposal for: [less than 10 words describing the work to be done]
Showing off community Dapp journeys
## What is this? 
-  @chadlamon  and I were approached with a cool idea from @mikedotexe  to showcase one of our community members building on NEAR. 
- We want to work with these members and provide our assistance and advice with creating their own "journey video" would be another cool way to show off the more "human" side of building on NEAR

## Who needs to be involved?
- @chadlamon 
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] Video 1 draft
- [ ] Video 1 Official
- [ ] Video 2 draft
- [ ]  video 2 official

## What t-shirt size is this? (range: multi-spint to 1 hour)
medium

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by crasskitty** [comment]
@doriancrutcher reminder to add all people working on this as assignees on the card :)

**Comment by crasskitty** [comment]
@doriancrutcher do you need someone to film for this? I have a community dev working on pluminite that might be down?

**Comment by cameron-NEAR** [comment]
Developer success testimonials are so crucial and I love this initiative

**Comment by chadlamon** [comment]
Im stoked for this one! We will know more after the first meeting & seeing what the talented kiddos can produce video wise for us

**Comment by doriancrutcher** [comment]
@cameron-NEAR Do you have any advice on how to reach out to potential video candidates. It seems like you would be someone who would know a lot about how to reach out to people and would love to pick your brain about it.

**Comment by cameron-NEAR** [comment]
Suggested Template:

"Hey {name}, I'm on the Developer Relations team at Near where I make
programming tutorials where I .....

Are you available on* {date} *from* {time} *to discuss {topic}? We normally
receive {x} views per episode and I can guarantee our viewers will love to
learn more about {topic details}.

I look forward to hearing from you!

Best,
Dorian"

**Comment by chadlamon** [comment]
I just sent elijah 4 tracks for him to use in the video, we should be seeing a first draft for the first video this week :)

**Comment by chadlamon** [comment]
Expecting the 1st rough draft this week!
