### ISSUE TITLE
[TASK] Build Library Of 1 Minute Micro Content Videos For Social

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#118]
# Proposal for: Starting our arsenal of postable micro content.

## What is this? 
- Creating marketable videos that will be highlighting a valuable feature NEAR has to offer & will contain a clear "gateway drug" AKA call to action for the viewer to Get started with NEAR.

## Who needs to be involved?
- @chadlamon 

## Tasks to complete 
- Piece together one 1 minute marketable video asset per day
- See if I can get the same point across but in a 16 second video to market in socials "stories" section
- Create a nuanced video resolution & format Template "guide" for NEAR

## What t-shirt size is this?
(Medium)

## What Priority is this?
- P2

**Comment by crasskitty** [comment]
@chadlamon reminder to assign yourself to this :)

**Comment by doriancrutcher** [comment]
I'm very happy to help assist with this. had a cool idea with chad o for a few ideas
