### ISSUE TITLE
[EPIC] Blockheads Ep:BlockCraft Pt 1 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#126]
# Proposal for: [less than 10 words describing the work to be done]

## What is this? 
- NFT Minecraft screenshot launcher! 
## Who needs to be involved?
- @chadlamon 
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] Create Frontend
- [ ] Implement matt's nft launcher 

## What t-shirt size is this? (range: multi-spint to 1 hour)
Medium

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
Im so excited for this!

**Comment by chadlamon** [comment]
I think we are going to have to start with Block-paw first. Its looking more bleak with the legal side of being able to deploy block-watch unfortunately lol </3
