### ISSUE TITLE
[EPIC] BlockHeads Rainbow Bridge for the Everyday Man

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#127]
# Proposal for: [less than 10 words describing the work to be done]
Let's make a rainbow bridge video for someone who'd completely new to the field of blockchain 
## What is this? 
There's a lot of hype around the rainbow bridge right now. Let's add to it and create one for the everyday average person that's new to blockchain. 

We'll cover everything from making a metamask to conducting the transaction across the chain. 

## Who needs to be involved?
- @chadlamon 
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] Get budget for large sum transfer over the chains and to account for all the fees 
- [ ] creating video

## What t-shirt size is this? (range: multi-spint to 1 hour)
small

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
How long are you thinking for this episode??

**Comment by chadlamon** [comment]
For my end to edit this I would consider it a Large shirt or medium
