### ISSUE TITLE
[EPIC] Onboard new team member

### ISSUE THREAD

**Issue by waverlymaven** [near/devrel#135]
# Proposal for: Onboard Elaine

## What is this? 
- Onboard our new team member Elaine and make sure she feels welcome! :)

## Who needs to be involved?
-Dani + Ecosystem team
-Bowen has agreed to be her onboarding buddy
-Thank you to Arpi for handling the opps side

## Tasks to complete (can return to [x] these)
- [ ] todo 
- [ ] todo 2

## What t-shirt size is this? (range: multi-spint to 1 hour)
Medium

## What priority is this? (remove what doesn't apply)

- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by chadlamon** [comment]
Lets make her feel welcome! :D
