### ISSUE TITLE
[EPIC] BlockBytes 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#145]
# Proposal for: [less than 10 words describing the work to be done]
Create mini content featuring apps, or dev tricks for programmers
## What is this? 

- Our social media accounts could use some beefing up with non committal content  to either promote what people are building on near, or get them excited to build. 
- Developers may be able to find tools in our near-api-js library that didn't know existed
- We can do a quick vid teasing to what is actually in an ERC-20 contract 
- Non-devs could see what cool apps are being developed on our protocol. 
## Who needs to be involved?
- @chadlamon 
- @nearlyalmonds 

## Tasks to complete (can return to [x] these)
- [ ] todo 
- [ ] todo 2

## What t-shirt size is this? (range: multi-spint to 1 hour)
medium to large

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
I really agree Dorian! Our social media accounts could use HUGE beefing up & should be posted on more frequently showcasing 1 minute videos of apps "I could easily pull from each episode of blockheads & use the ending of each episode that highlight what has been built".
