### ISSUE TITLE
[TASK] Document Token Balances 

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#157]
# Proposal for: document nuances of token balances

## What is this? 
- Olga has created a [doc](https://github.com/telezhnaya/docs/blob/master/docs/tokens/balances.md) laying out token balances. This needs to be enhanced and added to docs.

## Who needs to be involved?
- @thisisjoshford 

## Tasks to complete (can return to [x] these)
- [ ] enhance documentation as described in the recorded meeting with Olga

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P0 (EMERGENCY: drop everything to put out the fire)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
- P2 (Important: known docs, feature requests, or known bugs)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by bucanero** [comment]
All the token-related documents were moved to the Wiki.
I have also moved this "token balance" article to: https://wiki.near.org/getting-started/near-token/token-balances

I'm not sure if this task is still valid for DevRel or not? 🤔
