### ISSUE TITLE
[TASK] Grant Reviews

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#163]
# Proposal for: Review Grants

## What is this? 
- review several grants assigned in submitable 

## Who needs to be involved?
-  @thisisjoshford 

## Tasks to complete (can return to [x] these)
- [ ] review grants (timebox 20-30min ea)

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P0 (EMERGENCY: drop everything to put out the fire)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
- P2 (Important: known docs, feature requests, or known bugs)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by crasskitty** [comment]
hey @thisisjoshford is this related to the issue #167 that @doriancrutcher made or nah?
