### ISSUE TITLE
[Wallet Beta Club] End to end experience for NEAR wallet users

### ISSUE THREAD

**Issue by stefanopepe** [near/devrel#164]
# Proposal for: a community-oriented beta program for NEAR Wallet users

## What is this? 
The Wallet team is evolving the product at a very high pace - following a constantly changing ecosystem and a growing number of great product growth opportunities.
This initiative wants to structure the testing of wallet existing and new features, with the goal to streamline the last steps of a new feature journey - from the "beta" to the "generally available" phase.

As a Beta Club member, I feel engaged and important, as I can test early new Wallet features. I can also get some swag or tokens for my time!
As a Wallet team member, I can engage the community to provide early feedback and testing to any changes we apply to the product, such that I feel more confident that my work is valuable for them.

## Who needs to be involved?
- Me and @corwinharrell from the wallet team, to identify the tags/releases to submit and set the high-level rules
- The community team, to help with day-by-day communications and more specific rules (and the terms to get tokens)
- NEAR Foundation to streamline the grants allocation
- Dev resources to integrate together forms, emails, tables and verification tooling (e.g., count the times users really used the staging wallet)

## Tasks to complete (can return to [x] these)
- [ ] a dedicated page/guild initiative with instructions, rules and rewards. Should work as a waitlist, such that idle users are  removed and replaced with more engaged ones
- [ ] a mailing list that will receive semi-automated notifications when some new wallet pull-request lands on the "staging" url at https://wallet.staging.near.org , what is changed and what needs to be tested (eventually how!). This should be connected with more persistent content, such as: a github repo (or issues area) or a forum thread.
- [ ] a feedback collection form where Wallet Beta Club members can submit their findings, in the form of closed answers, recorded video, or other input (depending on the feature and the magnitude of the initiative). Might use Zendesk and its own [custom forms](https://nearhelp.zendesk.com/hc/en-us/requests/new?ticket_form_id=1500000226481) as well
- [ ] a chat channel (on Discord) where the Wallet Team can interact with the Beta Club members, asking questions or providing more detailed feedback
- [ ] a semi-automated bounty bot that transforms the work done by community members into tokens or other benefits (swag?), such that the Wallet Team doesn't have to audit hundreds (potentially thousands) of user submissions every week

## What t-shirt size is this? (range: multi-sprint to 1 hour)
medium to large

## What priority is this? (remove what doesn't apply)
- P2 (Important: known docs, feature requests, or known bugs)

Keep in mind that I plan to have a new "Beta Club Release" every four/six weeks, and I would like to see this happen at least once this quarter

**Comment by crasskitty** [comment]
@jimmy3dita when do you need this work completed?

**Comment by crasskitty** [comment]
Also @jimmy3dita whose help did you need here? I know when we discussed it, you needed my help-- anyone else from DevRel?

**Comment by jimmy3dita** [comment]
> Also @jimmy3dita whose help did you need here? I know when we discussed it, you needed my help-- anyone else from DevRel?

I don't have anyone specific in mind, but may require help from the team working on the metrics (Tiffany and Yifang):
1. measure the participation by wallet ID >> see who really used the staging wallet instead of the normal one, and how often
2. use the data collected at 1 to evaluate the engagement of single participants, and potentially replace them
3. put this information in one place (a table) and fetch some basic on-chain data
