### ISSUE TITLE
[DEVREL RESOURCE REQUEST] Tutorial how to query public indexer

### ISSUE THREAD

**Issue by ilblackdragon** [near/devrel#165]
# Proposal for: Tutorial how to query public indexer

## What is this? 
- Tutorial + blog post

How to use indexer, for example: 
 - Last 10 transactions for given account
 - What are top accounts by amount of funds
 - etc

## Who needs to be involved?
-

## Tasks to complete (can return to [x] these)
- [ ] Turn this https://github.com/near/near-indexer-for-explorer#shared-public-access — how to access on chain data via simple SQL queries into a tutorial / blog post with some examples on existing contracts.

## What t-shirt size is this? (range: multi-sprint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by potatodepaulo** [comment]
Hey @crasskitty how should be pull this in?

**Comment by crasskitty** [comment]
@potatodepaulo it looks like this will be @thisisjoshford and @nearlyalmonds resources who will be affected, is this correct/

If so, I will connect with each of them to determine what we will postpone to get this done :)

**Comment by crasskitty** [comment]
@ilblackdragon when do you need this work completed?

**Comment by ilblackdragon** [comment]
It's nice to have that people ask in NEAR Dev chat from time to time. No deadline on my side.

**Comment by crasskitty** [comment]
thanks @ilblackdragon

**Comment by think-in-universe** [comment]
@doriancrutcher Hey Dorian, there're a few examples here that may be helpful for the indexer tutorial: https://cookbook.near-x.org/indexer.html

**Comment by BenKurrek** [comment]
Some concerns with making a tutorial on how to query the public DB is that at the moment, almost the entire public replica is occupied and it's hard to connect. If we make a tutorial in docs, it will make it virtually impossible to connect unless something is upgraded. What are your thoughts on this @frol?

**Comment by frol** [comment]
Oh, wow https://cookbook.near-x.org/indexer.html - I feel this is already enough. I believe we should not do anything extra at the moment given the concerns already expressed above. Let's just make the link discoverable and close this until we have some sort of indexer as a service
