### ISSUE TITLE
[TASK] Grant Proposal Review 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#167]
# Proposal for: [less than 10 words describing the work to be done]

## What is this? 
Reviewing Grant proposals as they come in 
## Who needs to be involved?
- @doriancrutcher 

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)
small

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by crasskitty** [comment]
Hey @doriancrutcher did you plan to own this or would it be a @waverlymaven thing?
