### ISSUE TITLE
[EPIC] Voting App Tutorial Update

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#168]
# Proposal for: [less than 10 words describing the work to be done]

## What is this? 
- The Voting app tutorial video actually got a lot of views on it's own without any google ad campaigns. This was my second video I created a while ago so now the application is a bit out of date. I think it could be fun to recreate the tutorial in a more streamlined way with now a budget behind it 

## Who needs to be involved?
- @chadlamon 
- @doriancrutcher 

## Tasks to complete (can return to [x] these)
- [ ] todo 
- [ ] todo 2

## What t-shirt size is this? (range: multi-spint to 1 hour)
small 
## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
Great idea! Lets crush this one & launch it to mainnet as well ;)
