### ISSUE TITLE
[EPIC] OS TikTok

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#172]
# Proposal for: Open Sourcerers on TikTok

## What is this? 
- strategize and execute NEAR TikTok content

## Who needs to be involved?
-Mally
-Chad

## Tasks to complete 
- [ ] research crypto content on TikTok
- [ ] content backlog
- [ ] execution w/ team

## What t-shirt size is this? 
multi-sprint M

## What priority is this? (remove what doesn't apply)
P2

**Comment by chadlamon** [comment]
Ill start researching today! Could you message me the login info for the new account so that I can start engaging with others & getting people used to us?

**Comment by chadlamon** [comment]
Ill be able to have a video uploaded by the end of the week now that ive got some bandwidth
