### ISSUE TITLE
[Task] Pluminite intro video?

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#173]
# Proposal for: a teaser/ dmeo video for pluminite

## What is this? 
- A quick less than 30 second video to demo Pluminite to the world

## Who needs to be involved?
- @chadlamon @crasskitty 

## Tasks to complete (can return to [x] these)
- [x] create the story board
- [x] create the video

## What t-shirt size is this? (range: multi-spint to 1 hour)
medium

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
Lets sync this week on it! Ill give you my epidemic sound login info & you can find what royalty free track you would like for z teaser

**Comment by crasskitty** [comment]
@chadlamon sounds good. I have my own epidemic sound 😅 so I'll get started on this

**Comment by crasskitty** [comment]
Update: @chadlamon and I synced today on a story board and found music.
