### ISSUE TITLE
[EPIC] Blockheads Ep: Making of BlockCraft Pt 2

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#180]
# Proposal for: [less than 10 words describing the work to be done]
Creating second part 2 for new bh ep 
## What is this? 
- 

## Who needs to be involved?
- @chadlamon 

## Tasks to complete (can return to [x] these)
- [ ] todo 
- [ ] todo 2

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)

- P2 (Important: known docs, feature requests, or known bugs)

**Comment by chadlamon** [comment]
All about it!
