### ISSUE TITLE
[TASK] Near Escrow App release

### ISSUE THREAD

**Issue by zavodil** [near/devrel#187]
# Proposal for: 
Make a product using https://github.com/Kouprin/accounts-marketplace/tree/master/escrow_contract

## What is this? 
- New use case for blockchain and great demonstration of Near Account mode

## Who needs to be involved?
- 

## Tasks to complete (can return to [x] these)
- [ ]  validate contract
- [ ] create ui
- [ ] test ui
- [ ] deploy testnet/mainnet
- [ ] test with community
- [ ] release

## What t-shirt size is this? (range: multi-spint to 1 hour)
(large)

## What priority is this? (remove what doesn't apply)
- P2

**Comment by chadlamon** [comment]
Im loving this!
