### ISSUE TITLE
Weekly Forum Updates

### ISSUE THREAD

**Issue by jlwaugh** [near/devrel#2]
Hi DevReal team! I'm thinking about how to aggregate content for weekly updates on the forum, and I thought maybe we can use this particular issue to collaborate on that project. What would you like to see in regular dev updates?

___

_DRAFT_

Hi everyone! 

Thanks for joining us on the NEAR governance forum.

As you may know, one of the main goals for Near is greater accountability, utilizing the flexibility of contract-based structures and permissions. We are committed to sharing valuable and important resources with participants. Transparent collaboration facilitates coordination around shared goals of the whole NEAR ecosystem. This thread will begin a series of weekly updates, intended to bring people together and reward high-quality contributions.

## Summary

This January has been a considerable turning point for Near, and I'm excited to share what I've gathered thus far. NEAR is a truly great opportunity to learn and build with amazing humans! What a fascinating ecosystem of communities ✨ 

## Recent Blog Posts

https://near.org/blog/2020-near-in-review-ecosystem-tour

Early 2021 is bringing lots of exciting initiatives ~ you can follow along on Twitter and the governance forum to hear the latest. We are planning to announce the launch of the NEAR Grants Program, debut improvements to the NEAR community governance experience, and share exciting updates about the Rainbow Bridge 🌈 

## Most Referred Forum Topics

- [Planning for AssemblyScript support and integration for the next 6 months, starting Jan '21](https://gov.near.org/t/planning-for-assemblyscript-support-and-integration-for-the-next-6-months-starting-jan21/345)
- [Update on the new engineering management structure](https://gov.near.org/t/update-on-the-new-engineering-management-structure/374)
- [EVM Runtime base token](https://gov.near.org/t/evm-runtime-base-token/340)
- [Betanet Analisys Group Reports](https://gov.near.org/t/betanet-analisys-group-reports/339)
- [Berryclub chinese guild report](https://gov.near.org/t/berryclub-chinese-guild-report/367)

## Ecosystem Participation

Please reply to this post with an update on what you're doing, as it relates to the NEAR ecosystem 🙂 

Ask questions. Tell us about specific projects and goals. Share thoughts and feelings.

Your feedback is much appreciated!

**Comment by nearmax** [comment]
I would call it something like "Dev Community Updates" to differentiate from https://gov.near.org/t/2021-01-18-engineering-update/395/2

**Comment by jlwaugh** [comment]
Perhaps our dev (community) updates would be more interesting and engaging if they combine official enginearing updates from Max and the core devs with other updates from dev guilds and project leaders in our ecosystem? We could try organizing these updates in a weekly thread?

**Comment by mattlockyer** [comment]
@jlwaugh easy to source from here I think?
https://gov.near.org/t/devrel-weekly-update-19-jan-2021/406/2

This is quite literally going to be what devrel is doing that's applicable to the community.

e.g.

Engineering will do the technicals
DevEx will do the libraries, tools, standards
DevRel will develop the examples / determine pain points / source partner needs

Reporting on DevRel is enough right?
