### ISSUE TITLE
[EPIC] BlockHead Community Stories - Hawaii Tracker Family 

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#225]
## What is this for? 
- Showing off a family who's 15 year old created a Community Based Social Media App and plans to build on NEAR

## Who needs to be involved?
- @doriancrutcher 
- @chad

## Tasks to complete (can return to [x] these)
- [x] Script Review 
- [x] Recording 
- [x] Editing
- [ ] Posing 
## What is the scope of this? (range: x-small is 1 hour, x-large is over a month of work)
- [ ] medium

## What priority is this? (remove what doesn't apply)
- [ ] P2 (Important: known docs, feature requests, or known bugs)

**Comment by chad** [comment]
Wrong @chad :)

**Comment by chadlamon** [comment]
ill be automating the post today to be posted tomorrow!! :D
