### ISSUE TITLE
[DOCS] Thor's Feedback

### ISSUE THREAD

**Issue by potatodepaulo** [near/devrel#24]
Thor, [11.02.21 04:16]
a good tip to include in docs

Thor, [11.02.21 04:16]
when making cross contract calls to self

Thor, [11.02.21 04:16]

```Rust    
ext_self::transfer_from_dispatcher(
        &env::current_account_id(),
        NO_DEPOSIT,
        DEFAULT_GAS, // calls to self ignore "attached gas", used whole attached deposit
```
Thor, [11.02.21 04:16]
the gas argument is entirely ignored

Thor, [11.02.21 04:17]
A behavior reproducible with logging calls to "env::used|prepaid_gas()

Thor, [11.02.21 04:22]
ie, I may replace DEFAULT_GAS with any non-zero value; zero triggers a failed assertion in the transfer_from implementation, but would probably be fine otherwise

Thor, [11.02.21 04:25]
Btw, the reason one would have such a call to self is to chain with other promise-returning functions which is very useful, and possibly non obvious; satisfying the async pattern, ie:
```Rust
      .ext_transfer_from(offer.from.to_string(), unique_id.to_string())
      .then(ext_self::transfer_from_dispatcher(
      ```

**Comment by mikedotexe** [comment]
From today:

<img width="800" alt="Screen Shot 2021-02-25 at 12 09 35 PM" src="https://user-images.githubusercontent.com/1042667/109211108-9da0e600-7762-11eb-94dd-0ccc0c3b035b.png">

**Comment by ilblackdragon** [comment]
The original issue described sounds like a bug in near-sdk-rs and should be filed there @mikedotexe @evgenykuzyakov .

Lack of API documentation is similar an issue - we should add a pragma to enforce doc strings and generate API docs from code automatically.

The DevRel team should help with setting up the process to generate the docs and surface on docs.near.org, but @mikedotexe you guys are owners of the near-sdk-rs repo and should enforce having API documentation there in the first place.

**Comment by potatodepaulo** [comment]
Hey @mikedotexe wanted to bump this and see what the status was. Is this implemented in near-sdk-rs?

**Comment by mikedotexe** [comment]
Closing as we have this issue in the proper repo now
