### ISSUE TITLE
DeCash Tutorial (Decentralized Venmo)

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#271]
This tutorial will show users how to send near tokens using assembly script while being a relatable app to draw in new developers

**Comment by ilblackdragon** [comment]
Hey, so great issue to start exploring how we can track not just doing stuff but actually success.

Few things here:
 - Issue should have a goal, beyond what should be done. I would expect goals here would be to attract X people to read tutorial in 1st week, and generate Y reads later. It also can be about SEO impact. Questions answered and more.
 - Let's track in one issue these goals and related sub-tasks like editing video, publishing and more. This way we can still see that this is in progress, while some other sub-items are already have been launched.
 - For the goal there is still a single person responsible (Directly Responsible Person DRI) who this issue continues to be assigned.
 - Ideally something like this is created, there are also some information why this is important task - e.g. we have 3 developers asking for an example XYZ over past months. This way there will be more information to prioritize compared to other issues.
