### ISSUE TITLE
[MetaBUIDL] Hackathon submission form

### ISSUE THREAD

**Issue by ilblackdragon** [near/devrel#281]
Create hackathon submission form Airtable.

What are fields we need?
 - Team name
 - near account to receive prize
 -

**Comment by thisisjoshford** [comment]
Spoke with @jakestutzman and he will assist with the completion of this with the fields we need.

**Comment by think-in-universe** [comment]
any other fields to add? https://airtable.com/shrEA8zh9SkxIJqcc

**Comment by zavodil** [comment]
> any other fields to add? https://airtable.com/shrEA8zh9SkxIJqcc

Looks awesome! The only little update for Team Members section, may be we should not push every Team Member to create a github account, maybe paras/instagram profile will be enough for nft artists/etc.

**Comment by think-in-universe** [comment]
@zavodil thanks Vadim. good point. I have updated the description.

**Comment by thisisjoshford** [comment]
This looks great @think-in-universe ! Only minor suggestion would be maybe an optional field for presentation slides?

**Comment by think-in-universe** [comment]
@thisisjoshford sounds good. added.
