### ISSUE TITLE
Beta test near-runner

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#290]
Beta test [near-runner](https://github.com/near/runner-js) and provide feedback

- [x] @mehtaphysical 
- [x] @doriancrutcher 
- [x] @BenKurrek

**Comment by BenKurrek** [comment]
Creating a [feedback document](https://docs.google.com/document/d/1YbuRl9GdsxFz11EulDS0noeXCAdtzL146-oPjx2iHFI/edit?usp=sharing)

**Comment by thisisjoshford** [comment]
@mehtaphysical @doriancrutcher can you leave a feedback doc here for @chadoh and @willemneal ?

**Comment by doriancrutcher** [comment]
Here is my [feedback document](https://docs.google.com/document/d/1UZcm839gBh0C4dL8G0fNkTj4TAIVPn6D1IXd0xPw8iM/edit?usp=sharing)

**Comment by mehtaphysical** [comment]
[feedback](https://docs.google.com/document/d/1GGyMKC9_X4718WaJkcqE-K3KJlsuvXakJ9Ykd5J7VwU)

**Comment by thisisjoshford** [comment]
@chadoh @willemneal here is some recorded feedback on `near-runner` :)

**Comment by willemneal** [comment]
@mehtaphysical I can't get access to the doc.

**Comment by chadoh** [comment]
Can people please edit their comments here and paste their notes right inline, rather than making me click links to external documents? 🙂

**Comment by BenKurrek** [comment]
- Section 3 (boostrap) --> `path.join(__dirname, '..', 'path', 'to', 'compiled.wasm')` Is it possible to have path.join(__dirname, ‘insert path to compiled wasm’) 
- Currently section 3 has `describe('my contract'` and section 4 also has `describe('my contract'` if the describes are doing different things (first is deploying the contract) and the second is writing tests, maybe you could call the first one `describe('deploy contracts' and then the second` `describe('tests for contracts'`or something like that
