### ISSUE TITLE
EPIC - DevRel Interface for Internal / External Resource Requests

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#3]
Got something you think DevRel should build?
Partner you think a DevRel engineer should spend an hour with?

Follow these steps to best position your request and we'll get you answers ASAP!

[TODO discuss / determine actual steps]

1. Fill in this form
2. Qualify the project using this framework
3. Have a look at these resources: (a, b, c) would this person / project be better served by updating or expanding these?

**Comment by crazyrabbitLTC** [comment]
Hey folks, I'll keep this lean, but this is what comes to mind when I think about touching anything new in Blockchain land. 

How easy is it for me to get tokens? If it's hard, I'm not interested. I want to feel both: 

a) motivated from a financial point of view and 
b) like I can actually deploy things easily and do things easily.

I personally would't discount that first thing: a. For projects that have VC funding there is also a lingering sense that you might just be doing all this hard work to make some people you don't know rich. Skin in the game is a hugely important if it's not yet clear that the actual BUSINESS I try to build on Near will make money, it goes a long way to feel like, "my project might fail, but a rising tide raises all boats". The grants process goes a long way, I would be generous and lower the barrier to entry for it. Take a look at The Graph, they gave out 33,000 tokens to everyone who went through their curator bootcamp, (worth like $20,000 right now). Maybe do the same on Near. 

Web based tools to get up and started. Remix was my primary IDE for Solidity for years. If I don't know if I'm going to like the experience, I'm not going to invest in the setup necessary to find out I don't like the experience. Life is short. :-) 

Simplify the contract deployment process. With solidity + remix you are one click from deployment of a smart contract and interacting with it. 

I don't understand how the wallet works on NEAR, maybe making this clearer, or even making a metamask like browser plugin would help, if there isn't one already. Having a browser plugin isn't Awesome, but it does give me the sense that my ethereum wallet is always at hand. I can check my balances even without being on a Near website. 

Also I would personally lean into AssemblyScript, it's an easier journey from Ethereum than rust. The warning about Assembly script for financial applications might seem reasonable, but I think it scares off developers who would be more comfortable with AssemplyScript.  Yes AssemblyScript is new and might have risks, but so is Near. It seems hard to imagine that Assembly script smart contracts are more dangerous for a first time developer than a Rust smart contracts for a first time developer, on a new platform that is still evolving. :-) 

I'm always up to test things!

**Comment by mattlockyer** [comment]
Definitely some amazing thoughts here!

I'd like to move this to a gov discussion soon for an even wider community feedback outside of GH.

My summary notes are:
* can see financial benefits long term (e.g. token appreciation and value accrual)
* easy to try, build, test, deploy
* web based tools
* more wallet clarity and / or options
* lean into AssemblyScript because it's an easier language coming from Ethereum (and web dev)
