### ISSUE TITLE
Simple Account Model explanation

### ISSUE THREAD

**Issue by ilblackdragon** [near/devrel#304]
Account Model and Access Keys are still unclear.

There are 1h long videos explaining it, but a shorter explanation is needed. Ideally in Wiki and a quick video.

Here is a good analogy: https://docs.google.com/document/d/1gGGQrKS5twgiLEtgwP0PEZVG176K1Nea9lRgiDsFznA/edit

**Comment by thisisjoshford** [comment]
> Here's the article made by @doriancrutcher: https://wiki.near.org/overview/docs/access-keys
> 
> Update: due to recent Wiki issues, I had to re-submit this article, and now it's waiting to be merged.

Sounds good. Perhaps we should link to this article [here in docs](https://docs.near.org/docs/concepts/account) and also review this page for possible updates / enhancements.

**Comment by chadlamon** [comment]
Heres a 2 and a half minute video I put together with @doriancrutcher. It was finished a month ago, but I was assigned to METABUIDL & NEARCON so all other content got put on hold. 

https://www.dropbox.com/s/zpch1080s8zxkrs/Near%20Access%20Keys.m4v?dl=0
