### ISSUE TITLE
Create labeling system for support questions

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#319]

**Comment by BenKurrek** [comment]
This has been finished. Whenever a question is answered in the dev support channels, there are currently 14 different reactions that have been locked to the open-sourcerer role that you can flag the question as: 

FT questions - :ft:
NFT questions -  :nft: 
Rust questions - :rust: 
Assembly Script questions - :as: 
NAJ or Javascript questions - :js: 
Wallet questions - :wallet: 
NEAR CLI questions - :cli: 
Indexer questions - :indexer: 
Docs questions - :docs: 
DAO questions - :dao: 
Questions about examples - :example: 
Questions about keys - :keys: 
Bug related questions - :bugs: 
Misc questions - :magic:
