### ISSUE TITLE
NFT Tutorial

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#323]
The metaBUIDL hackathon feedback from devs has shown a huge interest in creating NFTs on NEAR and our NFT example on near.dev is confirming this by showing a lot of traffic. Let's pimp out this example to be suuuuper clean and clear for folks to use and learn from as well as create a tutorial that takes devs through the step-by-step process of minting their own NFT and getting it to display in NEAR Wallet. There has been some confusion around this process and common mistakes devs are making, so let's make it as easy as possible for them. :)

- [ ] Enhance and clean up code in [NFT example](https://examples.near.org/NFT) making it very easy to follow with clear comments in the codebase.
- [ ] Create a tutorial that walks through the creation of NFTs and displaying them in their wallet.

**Comment by BenKurrek** [comment]
I created a skeleton doc for how I think the tutorial should flow. This can be found [here](https://docs.google.com/document/d/1mQrpYGoG1uSM90aIDMSyr1gj9Xz_Q6pqKwgy0NlyHlM/edit?usp=sharing)
