### ISSUE TITLE
Fix NFT examples in `near-apps`

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#327]

**Comment by BenKurrek** [comment]
Created a document outlining some of the main things that each NFT example does. I also highlighted which ones I think are deprecated. Green means I think it should stay, yellow means I'm not sure, and red means I think it should go: 

https://docs.google.com/document/d/18Lg_LoCQUdaap6k7cCKsg6X6l49UD-2ute8a2EyP9nQ/edit?usp=sharing

**Comment by BenKurrek** [comment]
I'm doing a complete audit of the [nft-market ](https://github.com/near-examples/nft-market) repo through the 0 to hero NFT guide. This guide is a more structured version of the nft-market repo and contains fully commented and well-explained code. I've found a couple of logic errors and bugs in the market repo through this process so far and have put up PRs on the marketplace repo to fix them. 

When this 0 to hero guide is complete, I suggest removing the nft-market repo completely and replacing it with the 0 to hero NFT guide (which will include a marketplace contract).
