### ISSUE TITLE
Reach out to hackathon projects

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#334]
Continue relationships with hackathon submissions and coordinate with Guilds on this initiative. @zavodil to coordinate with Human Guild, India Guild, and China Guild.

Track outreach on this doc:
https://docs.google.com/spreadsheets/d/1wVZRxfunIiL7_ykb0001s-rcE2XROERfz-8Dg8deUTI/edit#gid=0

Hackathon Scorecards:
https://docs.google.com/spreadsheets/d/1h0eTGTWX2i-oeFgW2ca1UPqcVY4-FZCvI8CU8QkY6S8/edit#gid=1337295831

Hackathon Submissions:
https://airtable.com/shrDcq0Ozs9AJDTg7/tblg5F7OP62iYudxQ

**Comment by zavodil** [comment]
I created a [list with all projects and related activities ](https://docs.google.com/spreadsheets/d/1wVZRxfunIiL7_ykb0001s-rcE2XROERfz-8Dg8deUTI/edit#gid=1526105236)
