### ISSUE TITLE
Explore new near.org developer path and provide feedback

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#336]
https://near.flywheelstaging.com/

**Comment by doriancrutcher** [comment]
First impressions! The new webpage looks really slick and edgy. 





1.  Featured Items 
![image](https://user-images.githubusercontent.com/59028579/134718505-6fb8c6f0-bf58-4876-a1f1-dabedb1d108e.png)

I kinda want this featured component to have like it's own box or something. It just seems out of place to have the text floating off to the side like that 


2. Side Panel

Part of me thinks there should be an edgy side panel  for the animation section to all of this so I can click and get to the slide that interest me most? And it’ll also give me a quick overview of what’s on homepage at first glance 

3. Too much open space on scalablility  slide

![image](https://user-images.githubusercontent.com/59028579/134718895-5e3c528e-7385-48c4-bb6b-4910d36a659b.png)

I kinda feel like there’s too much open space here on this slide . Like the text here should be bigger, or there should be perhaps a list of featured companies that have taken advantage of the scalibilty, or something in the animation should be used to show the scalability. 

4 Mobile View

![image](https://user-images.githubusercontent.com/59028579/134719405-f640fd49-0687-4bca-bee5-71595e1fa429.png)


Mobile view looks a bit off in terms of the background. I know this one is probably a bit tricky but maybe it should be centered on the road? 


5. Menu
![image](https://user-images.githubusercontent.com/59028579/134719494-5a6f507d-116f-49c0-bb74-fb1ed86f0742.png)

This menu looks a lot better than our current one

6. Rainbow Bridge 
![image](https://user-images.githubusercontent.com/59028579/134719664-c3481fd1-6043-4cbd-8d11-43efd974ce6a.png)

I totally think there should be a "read more" button that leads to the docs here for the rainbow bridge
``

**Comment by zavodil** [comment]
there is a google doc for a website feedback, please join #website channel on a Near Inc Slack.

**Comment by bucanero** [comment]
> there is a google doc for a website feedback, please join #website channel on a Near Inc Slack.

I think that @thisisjoshford idea was mostly focused on developer path feedback

**Comment by danielwpz** [comment]
![image](https://user-images.githubusercontent.com/5139554/134836822-e81a81b8-c570-4daa-8929-618d8135714b.png)
in the node section, there is no actual guide about how to setup an rpc node, just a list of hardware requirements.
If the setup process is the same as other nodes at lease we should mention it and put a reference link

**Comment by think-in-universe** [comment]
> there is a google doc for a website feedback, please join #website channel on a Near Inc Slack.

I also added some comments in the google doc.
