### ISSUE TITLE
Blockcraft 2.0

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#337]
Block Craft 2.0 is coming alive 

We are working on a new version and method to make minecraft NFTS 

we will be pushing this out to the reddit minecraft community 

and other minecraft developer channels 

Super excited for this

**Comment by BenKurrek** [comment]
Updates - created a server and had chats with some interested developers who really want to help with the project. We also had chats with world edit devs but they were no help.

**Comment by BenKurrek** [comment]
Created a PR to move into docs --> https://github.com/near/docs/pull/881
