### ISSUE TITLE
Create new example contract / app: QuizChain

### ISSUE THREAD

**Issue by zavodil** [near/devrel#342]
Trustless quiz app with Rust contract and MeteorJS frontend
- new use case for a blockchain 
- NEAR adoption since every player needs Near Account
- new app for fun and community incentivises

Contract: https://github.com/zavodil/quizchain/
UI: quizchain.org
Documentation: Pending

Production: Pending (https://github.com/near/near-sdk-rs/issues/619)

**Comment by thisisjoshford** [comment]
Hey @zavodil ! Just checking in on the status of this issue.
