### ISSUE TITLE
Create boilerplate AS contract

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#354]
Create a boilerplate AS contract with well-commented code and a killer README that explains all the components and their uses.

**Comment by thisisjoshford** [comment]
@doriancrutcher When these issues are ready for review can you comment with a link to the project here? Not sure where to look :)

**Comment by doriancrutcher** [comment]
https://github.com/near-examples/NEAR-AS-Boilerplate

**Comment by thisisjoshford** [comment]
> https://github.com/near-examples/NEAR-AS-Boilerplate

Thanks for the link!  Took a look and have a few tasks that should be completed:

- [ ] Update version on SDK from `3.1.0` to the most current version `3.2.3`
- [ ] Add tests and implement CI using GithubActions
- [ ] It states there is a `compile` script but file does not appear anywhere on repo
- [ ] It states there is a `tests` script but file does not appear anywhere on repo

**Comment by doriancrutcher** [comment]
updated sdk

made readme more informative and accurate 

and added gh workflow
