### ISSUE TITLE
[Dev List] email typeform guild applicants with resources

### ISSUE THREAD

**Issue by crasskitty** [near/devrel#36]
Currently, we have a typeform with tons of responses asking to join a guild. 

We should email the people [here](https://airtable.com/tblDFtjNVnlCXBAih/viwNZGG7AEDIgDbGB?blocks=hide) with resources on available guilds to join, and then track which guilds they do join in the CRM.

To do this we will need a list of all active guilds and how to join them from @jlwaugh and possibly copywriting from @nearlyalmonds. @crasskitty can set up the contacts to port into the new mailchimp that Cameron set up and then auto email them all.

**Comment by nearlyalmonds** [comment]
I am happy to collaborate on this, I agree that it's important to standardize and make this process more effective.
