### ISSUE TITLE
Blockcraft blogpost pointing to Tutorial

### ISSUE THREAD

**Issue by bucanero** [near/devrel#363]

**Comment by thisisjoshford** [comment]
Can you share the blogpost draft @bucanero ?

**Comment by bucanero** [comment]
hello @thisisjoshford 

The original Blockcraft post (by @doriancrutcher) is here: https://medium.com/@dorian_54351/nfts-in-minecraft-with-near-21f034f4f2a2

I made a Google doc with some minor changes here: https://docs.google.com/document/d/12yIWBrYMvgeE0f-UdFpWyNIUi_XVfJ9IZvkW5j59FM0/edit

Btw, I don't know where we should publish these posts. Should these go to `near.org/blog`? or somewhere else?

**Comment by thisisjoshford** [comment]
Let's modify this blog post to have a third-person narrative @bucanero. Ideally, these will be posted on medium by the DevRel Team and a tweet will accompany it.

**Comment by bucanero** [comment]
> Let's modify this blog post to have a third-person narrative @bucanero. Ideally, these will be posted on medium by the DevRel Team and a tweet will accompany it.

gotcha, I'll re-work this blogpost draft. 
From Illia's feedback during the Devrel sync, we'll post them on `near.org/blog`. If we don't have access, we might need to ping the marketing team so they publish it for us.

**Comment by bucanero** [comment]
I have updated the draft to have a 3rd-person narrative ✅ 
(same google docs link)
