### ISSUE TITLE
The Graph -NEAR Testnet Blogpost

### ISSUE THREAD

**Issue by doriancrutcher** [near/devrel#434]
The Graph Just integrated the NEAR testnet into their environment! so now we can try out the indexer without paying for it. Going to update my blogpost tutorial 

https://hackmd.io/B3Z81nW6T_iJtadHnVw1pw?view

**Comment by thisisjoshford** [comment]
Working document: 
https://hackmd.io/monQ4SyaQDiOKjWc06qrQg
