### ISSUE TITLE
Add warning messages to NFT repos that are off standard.

### ISSUE THREAD

**Issue by BenKurrek** [near/devrel#436]
A lot of repositories are still off standard. I think it would be good to add warning messages to the READMEs of the repos that don't conform to the standard.

**Comment by BenKurrek** [comment]
Added a PR for pluminite: https://github.com/zavodil/pluminite-ui/pull/40

**Comment by BenKurrek** [comment]
Added a PR for the `nft-series` repo: https://github.com/near-examples/nft-series/pull/2

**Comment by BenKurrek** [comment]
Added a PR for the `nft-market` repo: https://github.com/near-examples/nft-market/pull/26

**Comment by BenKurrek** [comment]
Added PR for the `nft-onboarding` repo: https://github.com/near-examples/nft-onboarding/pull/6

**Comment by thisisjoshford** [comment]
all reviewed and merged
