### ISSUE TITLE
EPIC - APP - Practical Access Key Use Cases

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#5]
Essentially stealing this lovely full fledged example from @mikedotexe 

Beautiful example template and writeup here:
https://github.com/near/devx/issues/259

Problem:
We need an APP example that shows practical uses of access keys. It should "flex" different applications of access keys, doing things in the current best practice way, commented and then follow up with a subsequent tutorial, video, etc...

I'm not going to be as "prescriptive" as Mike's example but I'd like to see the following:
- key verification with a 3rd party service (backend server). Kind of like Mike's code example, but I would say OAuth is ok too (e.g. sign in with Google).
- key management e.g. add / delete / rotate access keys (because it's difficult to do correctly now given networking / RPC issues can cause loss of keys, so you need to build in recovery / backup options).
- backend signature verification (we get requests for this a lot and often send people to contract helper which is ok... but doesn't really explain / not commented what's happening so I worry about implementations being incorrect).
- ??? @amgando @thisisjoshford

**Comment by thisisjoshford** [comment]
- a dApp that creates a function access key that points to itself...  This could be created with an "invitation link" the user has demonstrating how function access keys allow for someone to interact with a dApp without ever having to create an account or even know they are using the chain.
