### ISSUE TITLE
Refactor docs to become developer centric

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#6]
- [ ]  relocate validator, tokens, & exchange documentation to subdomains or folders of near.org (have links in docs footer)
- [x] remove outdated / legacy documents
- [x]  reorganize docs following the outline below

---

**Basics**
- Key Concepts
- Papers
- Nomicon

**Develop**
- Smart Contracts
- ETH Compatability 
- Local Setup
- Contribute

**Tools**
- Wallet
- Explorer
- Stats
- near-cli
- near-api-js
- Examples

**API / RPC**
- endpoints

**Tutorials**
- Create transactions
- Issue a token
- Promise execution flow
- Cross contract calls
- Videos

**Community**
- Governance
- Guilds
- Discord, Telegram, StackOverflow

**FAQ**

**Comment by frol** [comment]
I really like the breakdown! I want to put my 2 cents here:

* near-api-js is not a tool like Wallet, Explorer, or near-cli (console utility); it is a library, so I would put in under Develop section
* I think API/RPC and near-api-js can be closer together under Develop -> Integration section (the naming should ideally reflect the fact that these APIs and libraries help to communicate with NEAR network [there are other `near-api-*` libraries: [`near-api-swift`](near-api-swift), [`near-api-unity`](near-api-unity), and [`near-api-py`](near-api-py)])
* It is not clear what Tool -> Examples could contain (I would expect to see examples under Develop -> Smart Contracts and Tutorials sections, but not in the Tools)

**Comment by ilblackdragon** [comment]
I think we should have language selectors in few different places, similar to https://devcenter.heroku.com/
RPC vs near-api-js is actually just different language. Where RPC is a JSON way to interact with the network.

Also selector of frontend vs contract is probably important. In contract it will be selector between Rust, AS and Solidity (Vyper?)

Also important sections like (https://devcenter.heroku.com/categories/reference): 
 - Architecture (might be better for Nomicon and Papers as they are not basics)
 - CLI -- it's really it's own thing
 - Troubleshooting and support -- this is where we can continuously add things that are complicated to figure out for better SEO
 - Patterns and Best Practices (Cookbook) -- this should contain suggested ways of doing common application patterns, and things like how to handle 30% fee, etc
 - Application Lifetime - testing, CI, launching on mainnet, post mainnet upgrades, monitoring, notifications, etc
 
 Generally I would also drive developers via next path:
 - Getting Started:
     1. Hello world on TestNet in first minute
     2. Learn to do other basic stuff like create an account to interact with that app -- explain keys / accounts stuff here
     3. Send transactions from CLI - learn how to login in CLI
 - Integrating existing on-chain application into frontend
     - Put a piece of JS into existing frontend to interact with the chain
    -  How to get create new frontend (select React, etc)
 - Writing your own contract
     - Selection of basic examples: a token, a chat, a calculator, etc
     - More advanced examples that explain patterns like DAOs
 - Launching an app on MainNet
     - Walk through steps to get an app on MainNet (including how to get an account on MainNet if they don't have one. Link to contract accounts@near.org to request to create a dev account)
     - Next steps: how to list it in awesomenear, get usage, etc.

**Comment by thisisjoshford** [comment]
> I think we should have language selectors in few different places, similar to https://devcenter.heroku.com/
> RPC vs near-api-js is actually just different language. Where RPC is a JSON way to interact with the network.
> 
> Also selector of frontend vs contract is probably important. In contract it will be selector between Rust, AS and Solidity (Vyper?)

I really like this approach! 

> Also important sections like (https://devcenter.heroku.com/categories/reference):
> 
> * Architecture (might be better for Nomicon and Papers as they are not basics)

Was actually thinking "Concepts" would be a better category for the "basics" section and could encompass all of this. 

**Concepts**
  - Basics
  - Papers
  - Nomicon

Rather than splitting the above up into two separate tabs ("Architecture" and "Basics") or perhaps I could have Architecture as a sub folder of Concepts with Papers and Nomicon inside.

> * Troubleshooting and support -- this is where we can continuously add things that are complicated to figure out for better SEO

Ahh yes, good idea. Would this take place of FAQ then?

> * Patterns and Best Practices (Cookbook) -- this should contain suggested ways of doing common application patterns, and things like how to handle 30% fee, etc

I'm imagining that this would be in tutorials... but also encompasses the next section of work I wanted to do in docs... documenting top 20 things smart contracts can "do" (provided by @mikedotexe ) :)

- add to a collection
- see if something is in a collection
- get from a collection
- remove from a collection
- make a cross-contract call
- make a cross-contract call and see if it succeeded
- make a cross-contract call and see if it succeeded and what the result was
- make a cross-contract call and see if it succeeded and what the result was and do a cross-contract call after that
- figure out who called the contract (signer/predecessor)
- do a factory deployment
- handle large numbers into methods as arguments
- return json formatted results
- return paginated results from a large collection
- accept deposits to payable methods
- make a "private" cross-contract call to ensure the promise succeeded
- "try catch finally" with promises
- initializing a contract
- upgrading a contract


> * Application Lifetime - testing, CI, launching on mainnet, post mainnet upgrades, monitoring, notifications, etc
> 

Ahh yes! Good stuff!

> Generally I would also drive developers via next path:
> 
> * Getting Started:
>   
>   1. Hello world on TestNet in first minute
>   2. Learn to do other basic stuff like create an account to interact with that app -- explain keys / accounts stuff here
>   3. Send transactions from CLI - learn how to login in CLI
> * Integrating existing on-chain application into frontend
>   
>   * Put a piece of JS into existing frontend to interact with the chain
>   * How to get create new frontend (select React, etc)
> * Writing your own contract
>   
>   * Selection of basic examples: a token, a chat, a calculator, etc
>   * More advanced examples that explain patterns like DAOs
> * Launching an app on MainNet
>   
>   * Walk through steps to get an app on MainNet (including how to get an account on MainNet if they don't have one. Link to contract [accounts@near.org](mailto:accounts@near.org) to request to create a dev account)
>   * Next steps: how to list it in awesomenear, get usage, etc.

I really like this flow, but I think it starts to enter the realm of near.org/learn... I'm happy to have this in docs, but don't want to create something that duplicates another platform we are building out. I think we need an executive decision on what belongs in docs and what belongs in near.org/learn. 

My mental model was: 
docs -> NEAR wiki / code snippets
NEAR U / near.org/learn -> tutorials, workshops, walkthroughs

Thanks for all the feedback @ilblackdragon ! 🙏

**Comment by thisisjoshford** [comment]
> * It is not clear what Tool -> Examples could contain (I would expect to see examples under Develop -> Smart Contracts and Tutorials sections, but not in the Tools)

Thanks so much for the feedback @frol ! The examples would just be a link to near.dev or links to near.dev individual projects... was thinking of this as a tool or common reference point for devs.

**Comment by thisisjoshford** [comment]
> > Generally I would also drive developers via next path:
> > 
> > * Getting Started:
> >   
> >   1. Hello world on TestNet in first minute
> >   2. Learn to do other basic stuff like create an account to interact with that app -- explain keys / accounts stuff here
> >   3. Send transactions from CLI - learn how to login in CLI
> > * Integrating existing on-chain application into frontend
> >   
> >   * Put a piece of JS into existing frontend to interact with the chain
> >   * How to get create new frontend (select React, etc)
> > * Writing your own contract
> >   
> >   * Selection of basic examples: a token, a chat, a calculator, etc
> >   * More advanced examples that explain patterns like DAOs
> > * Launching an app on MainNet
> >   
> >   * Walk through steps to get an app on MainNet (including how to get an account on MainNet if they don't have one. Link to contract [accounts@near.org](mailto:accounts@near.org) to request to create a dev account)
> >   * Next steps: how to list it in awesomenear, get usage, etc.
> 
> I really like this flow, but I think it starts to enter the realm of near.org/learn... I'm happy to have this in docs, but don't want to create something that duplicates another platform we are building out. I think we need an executive decision on what belongs in docs and what belongs in near.org/learn.
> 
> My mental model was:
> docs -> NEAR wiki / code snippets
> NEAR U / near.org/learn -> tutorials, workshops, walkthroughs
> 
> Thanks for all the feedback @ilblackdragon ! 🙏

Chatted with some colleagues during DevX standup about this part on Friday and think we can go with docs having small short guides / tutorials / walkthroughs and NEAR U being a more in-depth / deep dive into the material. Going to have a DevRel sync this morning and will make sure this is brought up as well as the status of near.org/learn / NEAR U.

**Comment by almal** [comment]
Hello everyone, this Sasha Baksht, of LEARN.NEAR

> docs -> NEAR wiki / code snippets
NEAR U / near.org/learn -> tutorials, workshops, walkthroughs

Would we agree in this approach:
**DOCS.NEAR** - Wiki/code snippets organized with consideration of NEAR  User Roles Basic(User)->Intermediate(Dapp UX dev)->Advanced (SC dev)->Expert(Core Dev) to be used as reference source for self

**LEARN.NEAR** - tutorials (SEO ready), workshops, courses and learning paths, with community learning and initially based on DOCS.NEAR as verified source of info. Shall be used for automated onboarding users of all kinds to NEAR ecosystem/community.

Makes sense?

**Comment by thisisjoshford** [comment]
> Hello everyone, this Sasha Baksht, of LEARN.NEAR
> 
> > docs -> NEAR wiki / code snippets
> > NEAR U / near.org/learn -> tutorials, workshops, walkthroughs
> 
> Would we agree in this approach:
> **DOCS.NEAR** - Wiki/code snippets organized with consideration of NEAR User Roles Basic(User)->Intermediate(Dapp UX dev)->Advanced (SC dev)->Expert(Core Dev) to be used as reference source for self
> 
> **LEARN.NEAR** - tutorials (SEO ready), workshops, courses and learning paths, with community learning and initially based on DOCS.NEAR as verified source of info. Shall be used for automated onboarding users of all kinds to NEAR ecosystem/community.
> 
> Makes sense?

Absolutely! Thanks for the feedback! :)
