### ISSUE TITLE
[EPIC] DevRel Twitter Presence: Engage

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#61]
# Proposal for: Aligning on a strategy and responsibilities for the developer-specific Twitter account @neardevs 

## What is this? 
This is an epic in the sense that it will continue, theoretically, for a very long time; for this quarter, the goal is to grow the follower count from 700 to 5,000 by expanding the output and making it feel essential. Our goal for this sprint is to align on the strategy and our respective duties for contributing to @neardevs. It will be an ongoing workstream that will be a small workload slice for all involved once we have agreed on the plan. 

## Who needs to be involved?
@chadlamon @cjd425 @nearlyalmonds @jlwaugh 

## Tasks to complete
[ ] - align on proposed content strategy and individual responsibilities 
[ ] - arrive at agreement for sharing this work with James from Community
[ ] - agree on a set of rules and conduct and social media guidelines (share with Legal)
[ ] - share login information with relevant contributors
[ ]. - surface said strategy to the team for feedback, then to community/marketing/beyond
[ ] -  align on a posting schedule and/or cadence with the goal of minimizing bureaucracy/planning and maximizing creativity/flexibility/agility

## What t-shirt size is this?
- [x ] medium

## What priority is this?
- [x] P2 (Important: known docs, feature requests, or known bugs)

**Comment by crasskitty** [comment]
@nearlyalmonds friendly reminder to assign yourself on your own issues! :)

That being said, it sounds like this Epic is to "grow the follower count from 700 to 5,000".

I would say this is a medium tshirt size, and probably agree that is a p2!

**Comment by cjd425** [comment]
I love it and see think this is a perfect channel to push our various opportunities (grants, BlockHead videos, bounties, open-roles at affiliated projects, hackathon info, etc). Also, I like this as a great cross-team initiative :D

**Comment by chadlamon** [comment]
Making big moves! I love the proposal & agree that it is indeed an epic that will require a good plan to execute effectively

**Comment by crasskitty** [comment]
@cameron-NEAR is waiting on direction from @nearlyalmonds
