### ISSUE TITLE
[TASK] ETHDenver devs user research sprint

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#62]
# Proposal for: User Research working group sprint to interview ETHDenver developers

## What is this? 
- We want to get feedback about the NEAR hackathon experience from developers who either hacked or considered hacking on NEAR at ETHDenver. This includes create-near-app, the getting started guide, and understanding blockers for ETH-native engineers interested in NEAR.

## Who needs to be involved?
-@cjd425 @jlwaugh @yu1ian @TiffanyGYJ @nearlyalmonds 

## Tasks to complete
[ ] - outreach to assigned list 
[ ] - follow-ups over next week following outreach
[ ] - conduct interviews (45m-1h) and save for transcription
[ ] - discuss learnings and outputs (Mally/Yulian lead)

## What t-shirt size is this?
- [x ] medium

## What priority is this?
[x ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
Nice, totally down with soliciting dev feedback so we can learn and grow :)
