### ISSUE TITLE
[EPIC] YouTube organization

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#66]
# Proposal for: organizing and optimizing the NEAR YouTube 

## What is this? 
- A multi-week plan to organize, optimize, streamline, and enhance the YouTube. This is an extremely important channel for NEAR that could use more effective attention and ownership, so we are lucky that Chad is here. Matt is a high-frequency contributor whose input will help a lot (along with @evgenykuzyakov) and Mally can guide/contribute/support.

## Who needs to be involved?
- @mattlockyer @chadlamon @nearlyalmonds 

## Tasks to complete
[ ] - YouTube audit (with Camille)
[ ] - reorganize playlists 
[ ] - standardize series and descriptive copy for SEO
[ ] - add timestamps and subtitles 
[ ] - add disclaimers to outdated content 
[ ] - publish guidelines/requirements to standardize all new content 

## What t-shirt size is this?
- [ ] medium

## What priority is this?
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by chadlamon** [comment]
Im all about it! Starting with the youtube audit is the perfect start. Great idea mally!

**Comment by thisisjoshford** [comment]
Yes!!! Our youtube page needs organization bad!!! :) 100% in on this one
