### ISSUE TITLE
[EPIC] Ep.9 BlockBop Music App Episode

### ISSUE THREAD

**Issue by chadlamon** [near/devrel#72]
## What is this? 
- Essentially a live streamed tiny desk concert & competition DAP for musicians, dj's & producers of all skill levels. The audience / users participate by using NEAR tokens to upvote artists. Upvotes = Listens. The 3 musicians with the most listens win NEAR tokens or other prizes TBD. A blockheads episode will also be created showcasing the fun & potential of NEAR protocol & can be heavily used for marketing.

## Who needs to be involved?
- DEV: @doriancrutcher 
- Event Assistance: @nearlyalmonds 
- Musicians: @chadlamon 

## Tasks to complete
[ ] - The Application
[ ] - BlockHeads Edit
[ ] - Practice run
[ ] - Launch App
[ ] - Drop Video

## What t-shirt size is this?
- [ ] large 

## What priority is this?
- [ ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by thisisjoshford** [comment]
Interesting concept! I wonder if creating an NFT "vote" token would be a better option than voting with actual NEAR tokens. Maybe you get one - three vote tokens when signing up and if you want more votes you would have to tweet about the contest or some other task that could be verified with a smart contract.

**Comment by nearlyalmonds** [comment]
Really excited to help out with this! I'm not at all skilled in running events so we may need to bring in additional help for this one, maybe from @crasskitty?
