### ISSUE TITLE
[EPIC] Meta Scoping & Estimation

### ISSUE THREAD

**Issue by mattlockyer** [near/devrel#76]
Proposal for: Meta Scoping & Estimation
What is this?
Watch and learn how the team scopes and estimates technical work. Figure out what works and doesn't in this process. GOAL to provide a better team guide, framework, exercises to estimate sprints.

Who needs to be involved?
- Matt
- Peter
- Sherif

Tasks to complete
- Breakdown of first sprint planning, epics, tasks, do we think we have a good size?
- Study progress and keep notes during sprint
- Retro spring scoping and estimation for team

What t-shirt size is this?
Large

What priority is this?
 P0 (EMERGENCY: drop everything to put out the fire)
 P1 (Critical: docs, bugs, or features that block work or dev/app success)
 P2 (Important: known docs, feature requests, or known bugs)
 [X ] P3 (Nice-to-have: docs or features that improve a flow)

**Comment by crasskitty** [comment]
need to clean up/ understand
