### ISSUE TITLE
Bridge + Faucet Demo video (1-3 mins)

### ISSUE THREAD

**Issue by yu1ian** [near/devrel#85]
# Proposal for: [less than 10 words describing the work to be done]
Edit the video
## What is this? 
Bridge Demo

## Who needs to be involved?
Chad Lamon

## Tasks to complete (can return to [x] these)
- [ ] edit video 

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by chadlamon** [comment]
Im all about it! I know the plan is to have it done by thursday evening. Are we going to upload and market this video asset to all of NEAR's social media outlets?

**Comment by yu1ian** [comment]
Potentially not right away (will have a more definitive answer tmrw). We want to include it in announcement article first. @chadoh can you please share your part once it is ready?
