### ISSUE TITLE
[EPIC] NFT Collateral & Positioning

### ISSUE THREAD

**Issue by nearlyalmonds** [near/devrel#86]
# Proposal for: NFT collateral & positioning

## What is this? 
- Detailed materials on NEAR NFTs for sharing externally.

## Who needs to be involved?
-Mally + Peter 

## Tasks to complete (can return to [x] these)
- [ ] for artists 
- [ ] for users
- [ ] for founders

## What priority is this? (remove what doesn't apply)
P1

**Comment by potatodepaulo** [comment]
Can you update the title as well please? It should look like "[EPIC] NFT Collateral & Positioning" or along those lines.

**Comment by crasskitty** [comment]
@potatodepaulo @nearlyalmonds I went ahead and did it :)

**Comment by nearlyalmonds** [comment]
Oooops, forgot the most important part. Thank you, Ash.

**Comment by crasskitty** [comment]
@nearlyalmonds @potatodepaulo --does this relate at all to the epic I am working on with Pluminite? https://github.com/near/devrel/issues/43
