### ISSUE TITLE
[DOC] walkthrough for buying NEAR using ETH

### ISSUE THREAD

**Issue by thisisjoshford** [near/devrel#88]
## What is this? 
- We need to make a video and written guide by end of Thurs for buying NEAR using ETH.

## Who needs to be involved?
- @thisisjoshford 

## Tasks to complete (can return to [x] these)
- [x] create written walkthrough @chloe has created an awesome one [here](https://createbase.community/2021/03/19/how-to-purchase-near-if-you-are-based-in-the-united-states)
- [x] add to docs

## What t-shirt size is this? (range: multi-spint to 1 hour)
(x-large, large, medium, small, x-small)

## What priority is this? (remove what doesn't apply)
- P0 (EMERGENCY: drop everything to put out the fire)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)
- P2 (Important: known docs, feature requests, or known bugs)
- P3 (Nice-to-have: docs or features that improve a flow)

**Comment by zavodil** [comment]
Could you consider related guide for https://faucet.paras.id/ please

**Comment by yu1ian** [comment]
@thisisjoshford are you going to make a video as well or should we also involve @chadlamon? I think timeline shifted a little so we have a bit more time

**Comment by thisisjoshford** [comment]
> @thisisjoshford are you going to make a video as well or should we also involve @chadlamon? I think timeline shifted a little so we have a bit more time

I am doing a video for this. Was told I needed it by tomorrow... has this changed @yu1ian ?

**Comment by yu1ian** [comment]
I thought FE is not ready yet. If it is, then tmrw is great

**Comment by chadlamon** [comment]
Let me know if you need help with this josh!
