### ISSUE TITLE
[TASK] Create a guide and video for ref finance Eth --> NEAR

### ISSUE THREAD

**Issue by potatodepaulo** [near/devrel#89]
## What is this? 
- a video and a guide walking through buying NEAR using Eth through the Ref Finance AMM. 

## Who needs to be involved?
- A person who knows how to get Eth and can figure out the ref finance api using a terminal within a couple of days.

## Tasks to complete (can return to [x] these)
- [ ] Get some Eth (from Peter)
- [ ] Read the docs https://ref-finance.gitbook.io/ref-finance/
- [ ] Successfully

## What priority is this? (remove what doesn't apply)
- P1 (Critical: docs, bugs, or features that block work or dev/app success)

**Comment by chadlamon** [comment]
Love the idea! I can edit the video assets when we get to that point.

**Comment by thisisjoshford** [comment]
closing this issue as it was already filed here near/devrel/issues/89
